### ISSUE TITLE
RHEL 10 beta does not support "hash" tables

### ISSUE THREAD

**Issue by iay** [robertdebock/ansible-role-postfix#38]
# Describe the bug

The Red Hat Enterprise 10 beta doesn't work with this role. The underlying issue seems to be a choice by Red Hat to remove the `hash` database type in advance of its removal by Postfix (RHEL 10 beta ships with `postfix` 3.8.5 but as I understand it this version still supports this database type; perhaps 3.9 does not.)

## Playbook

Please paste the playbook you are using. (Consider `requirements.yml` and
optionally the command you've invoked.)

```yaml
    - role: robertdebock.postfix
      vars:
        postfix_aliases:
          - name: root
            destination: ian@iay.org.uk
        postfix_relayhost: "[smarthost.cs.iay.org.uk]:25"
```

## Output

Various references to the `hash` database type being unsupported alongside suggestions to install the `postfix-hash` package (which does not exist) as a possible workaround.

In practice, replacing `hash` with `lmdm` throughout `main.cf.j2` along with adding the following explicitly fixed things for me, at least for now:

```
alias_maps = lmdb:/etc/aliases
...

default_database_type = lmdb
```

I've characterised this as a bug, but it's really just a "heads up" in case you want to look into it. I realise it's not reasonable to expect you to support a beta release: this might, after all, turn out not to be a problem in the final release later this year.

If this persists in the final release, I can come back with more detail and maybe a PR.
