### ISSUE TITLE
Taking away setgid makes sendmail fail

### ISSUE THREAD

**Issue by wzzrd** [robertdebock/ansible-role-postfix#7]
## Describe the bug
On all of Debian Buster, Fedora 33 and RHEL8 at least, the "set group owner" task takes away various setgid and sticky bits makes sendmail fail with variations off the following error:

```
 postdrop: warning: mail_queue_enter: create file maildrop/441438.29415: Permission denied
```

## Playbook
The listed bit of playbook sets the octal mode for the listed files to 0755, but from the deb / rpm, the files actually have the pemissions listed below:

```
  - name: set group owner                                                                                                                                                                                 
    file:                                                                                    
      path: "{{ item }}"                                                                     
      group: "{{ postfix_group }}"                                                           
      mode: "0755"                                                                           
    loop:                                                                                    
      - /usr/sbin/postqueue                                                                  
      - /usr/sbin/postdrop                                                                   
      - /var/spool/postfix/public                                                            
      - /var/spool/postfix/maildrop   
```

## Original permissions
On Debian Buster:
`/usr/sbin/postdrop` and `/usr/sbin/postqueue` are setgid (both 2555). `/var/spool/postfix/maildrop` has the sticky bit set (mode 1730), while `/var/spool/postfix/public` is setgid (mode 2710) 

On Fedora 33 and RHEL8:
Both `/usr/sbin/postdrop` and `/usr/sbin/postqueue` are setgid (both 2755). `/var/spool/postfix/maildrop` and `/var/spool/postfix/public` are mode 0730 and 0710, respectively.

## Output
After running the playbook, setgid is dropped from the `postqueue` and `postdrop` binaries, meaning the directories under `/var/spool/postfix` are no longer writable for postdrop processes. This leads the the aforementioned error.

## Environment
RHEL8, Fedora 33 and Debian Buster clients.

I'm most curious about why the permissions are changed in the first place. Is there something I am missing that could easily remedy this problem?
